/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.HashMapHandling.DateStagistic;
import controler.Main;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static javax.swing.SwingConstants.BOTTOM;
import static javax.swing.SwingConstants.CENTER;

/**
 *
 * @author Vu Ngoc Chi
 */
public class GDAnhViet extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form GDVietAnh
     */
    public GDAnhViet() throws IOException {
        initComponents();
        Main.LoadAV();
        buttonTC.addActionListener(this);
        buttonThoat.addActionListener(this);
        buttonTK.addActionListener(this);
        buttonVA.addActionListener(this);
        ArrayList<DateStagistic> arr = new ArrayList();
        //Chạy thử DateStagistic();
        arr = Main.mapAV.getDateStagistic();
        for(int i=0;i<arr.size();i++)
        {
            System.out.println(arr.get(i).getDate()+" đã học "+arr.get(i).getCount()+" từ");
        }
        //Sẽ in ra trong console
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonTK = new javax.swing.JButton();
        buttonThoat = new javax.swing.JButton();
        buttonTC = new javax.swing.JButton();
        Lbanh = new javax.swing.JLabel();
        buttonVA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(130, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconAV.jpg"))); // NOI18N

        buttonTK.setBackground(new java.awt.Color(255, 102, 153));
        buttonTK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonTK.setForeground(new java.awt.Color(0, 0, 255));
        buttonTK.setText("Tìm Kiếm");

        buttonThoat.setBackground(new java.awt.Color(0, 255, 0));
        buttonThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonThoat.setForeground(new java.awt.Color(153, 0, 0));
        buttonThoat.setText("Thoát");

        buttonTC.setBackground(new java.awt.Color(0, 255, 0));
        buttonTC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonTC.setForeground(new java.awt.Color(153, 0, 0));
        buttonTC.setText("Trang Chủ");

        Lbanh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Lbanh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Lbanh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonVA.setBackground(new java.awt.Color(0, 255, 0));
        buttonVA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonVA.setForeground(new java.awt.Color(153, 0, 0));
        buttonVA.setText("Việt - Anh");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(487, 487, 487)
                .addComponent(Lbanh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTK)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonThoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonTC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(buttonVA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(128, 128, 128)
                .addComponent(Lbanh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(buttonVA)
                .addGap(18, 18, 18)
                .addComponent(buttonTC)
                .addGap(26, 26, 26)
                .addComponent(buttonThoat)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            buttonTKClick();
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDAnhViet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDAnhViet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDAnhViet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDAnhViet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GDAnhViet().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GDAnhViet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbanh;
    private javax.swing.JButton buttonTC;
    private javax.swing.JButton buttonTK;
    private javax.swing.JButton buttonThoat;
    private javax.swing.JButton buttonVA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(buttonTK))
            buttonTKClick();
        else if(e.getSource().equals(buttonTC))
            buttonTCClick();
        else if(e.getSource().equals(buttonVA))
            buttonVAClick();
        else buttonThoatClick();
    }
    public void buttonTKClick(){
        String en = jTextField1.getText();
        String vn = new String();
        String concat = new String();
        ImageIcon icon;
        if(Main.mapAV.containsKey(en)==false) {
            concat = "Word can not found";
            icon = new ImageIcon(getClass().getResource("/data/noimg.jpeg"));
        }
        else
        {
        vn = Main.mapAV.getmapVn(en);
        concat = Main.mapAV.getmapPrn(en) + " : " + vn;
        try
            {
            icon = new ImageIcon(getClass().getResource("/data/"+en+".jpeg"));
            }
        catch(Exception eee)
            {
                icon = new ImageIcon(getClass().getResource("/data/noimg.jpeg"));
            }
        }
        Lbanh.setIcon(icon);
        Lbanh.setText(concat);
        Lbanh.setHorizontalTextPosition(CENTER);
        Lbanh.setVerticalTextPosition(BOTTOM);
        
    }
    public void buttonVAClick(){
        try{
        new GDVietAnh().setVisible(true);
        }
        catch(Exception ee){}
        this.dispose();
        
    }
    public void buttonTCClick(){
        new GDTrangChu().setVisible(true);
        this.dispose();
        
    }
    public void buttonThoatClick(){
        System.exit(0);
        
    }

}
