/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.Excel;
import controler.Main;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jxl.read.biff.BiffException;
import jxl.write.WriteException;
import model.word;
import controler.HashMapHandling;
import static controler.Main.MakeFilePath;
/**
 *
 * @author Vu Ngoc Chi
 */
public class GDQLBTV extends javax.swing.JFrame{

    /**
     * Creates new form GDQLBTV1
     */
    public  ArrayList<String> listTu = new ArrayList<>();
    public String En = new String();
    public String CN = new String();
    public GDQLBTV() throws IOException {
        initComponents();     
        for(int i = 0; i<Main.listChuDe.size(); i++){
            cbbCD.addItem(Main.listChuDe.get(i));
        }
        cbbCD.addItem("Tạo bộ từ vựng");
        jPanel2.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LbXoaOrTD = new javax.swing.JLabel();
        LbNghĩa = new javax.swing.JLabel();
        LbPA = new javax.swing.JLabel();
        textNghia = new javax.swing.JTextField();
        textPA = new javax.swing.JTextField();
        LbAnh = new javax.swing.JLabel();
        buttonHD = new javax.swing.JButton();
        buttonHuy = new javax.swing.JButton();
        buttonChon = new javax.swing.JButton();
        LbNew = new javax.swing.JLabel();
        textNew = new javax.swing.JTextField();
        cbbTu = new javax.swing.JComboBox<>();
        LbBTV = new javax.swing.JLabel();
        textBTV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        buttonTC = new javax.swing.JButton();
        buttonThoat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbbCD = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbbDSTV = new javax.swing.JComboBox<>();
        buttonBD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        LbXoaOrTD.setText("Từ cần sửa:");

        LbNghĩa.setText("Nghĩa: ");

        LbPA.setText("Phiên âm:");

        textNghia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNghiaActionPerformed(evt);
            }
        });

        textPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPAActionPerformed(evt);
            }
        });

        LbAnh.setText("Hình ảnh:");

        buttonHD.setBackground(new java.awt.Color(255, 255, 255));
        buttonHD.setText("Hướng dẫn");
        buttonHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHDActionPerformed(evt);
            }
        });

        buttonHuy.setBackground(new java.awt.Color(51, 255, 204));
        buttonHuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonHuy.setForeground(new java.awt.Color(102, 0, 0));
        buttonHuy.setText("Hủy");
        buttonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHuyActionPerformed(evt);
            }
        });

        buttonChon.setBackground(new java.awt.Color(51, 255, 204));
        buttonChon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonChon.setForeground(new java.awt.Color(102, 0, 0));
        buttonChon.setText("jButton2");
        buttonChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChonActionPerformed(evt);
            }
        });

        LbNew.setText("Chính sửa:");

        textNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNewActionPerformed(evt);
            }
        });

        cbbTu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbTuItemStateChanged(evt);
            }
        });

        LbBTV.setText("Bộ từ vựng");

        textBTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBTVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(155, Short.MAX_VALUE)
                        .addComponent(buttonChon, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(buttonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbBTV, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textBTV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbXoaOrTD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(LbNghĩa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LbPA)
                                            .addComponent(LbNew, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(cbbTu, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textNghia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textPA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(textNew, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbXoaOrTD)
                    .addComponent(cbbTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNew)
                    .addComponent(textNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNghĩa)
                    .addComponent(textNghia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbPA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHD))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbBTV)
                    .addComponent(textBTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonChon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/moi.jpg"))); // NOI18N

        buttonTC.setBackground(new java.awt.Color(0, 255, 51));
        buttonTC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonTC.setForeground(new java.awt.Color(153, 0, 0));
        buttonTC.setText("Trang Chủ");
        buttonTC.setActionCommand("");
        buttonTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTCActionPerformed(evt);
            }
        });

        buttonThoat.setBackground(new java.awt.Color(0, 255, 51));
        buttonThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonThoat.setForeground(new java.awt.Color(153, 0, 0));
        buttonThoat.setText("Thoát");
        buttonThoat.setActionCommand("");
        buttonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThoatActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Chọn bộ từ vựng");

        cbbCD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbbCD.setForeground(new java.awt.Color(0, 0, 204));
        cbbCD.setToolTipText("");
        cbbCD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbCDItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Chọn thao tác");

        cbbDSTV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbbDSTV.setForeground(new java.awt.Color(0, 0, 153));
        cbbDSTV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thêm Từ", "Sửa Từ", "Xóa Từ", "Ghép Bộ Từ Vựng", "Xóa Bộ Từ Vựng" }));
        cbbDSTV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbDSTVItemStateChanged(evt);
            }
        });
        cbbDSTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbDSTVMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbDSTV, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbCD, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbCD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbDSTV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        buttonBD.setBackground(new java.awt.Color(0, 153, 204));
        buttonBD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonBD.setForeground(new java.awt.Color(204, 0, 0));
        buttonBD.setText("Bắt Đầu");
        buttonBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(buttonBD))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonThoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(buttonBD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(buttonTC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(buttonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNghiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNghiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNghiaActionPerformed

    private void textPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPAActionPerformed

    private void textNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNewActionPerformed

    private void buttonTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTCActionPerformed
        new GDTrangChu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonTCActionPerformed

    private void buttonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonThoatActionPerformed

    private void cbbDSTVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbDSTVMouseClicked
        
            
    }//GEN-LAST:event_cbbDSTVMouseClicked

    private void buttonBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBDActionPerformed
        Main.selection = cbbCD.getSelectedItem().toString();
        CN = cbbDSTV.getSelectedItem().toString();
        listTu.clear();
        Main.mapAV1.clear();
        Main.LoadAV1();
        if(CN.equals("Ghép Bộ Từ Vựng")){
            listTu = Main.listChuDe;
            listTu.remove(Main.selection);
        }
        else{
        listTu = Main.mapAV1.toArrayList();} 
        cbbTu.removeAllItems();
        for(int i = 0 ;i< listTu.size(); i++)
            cbbTu.addItem(listTu.get(i)); 
        
        if(CN.equals("Thêm Từ")){
            ThemTu();
        }
        else if(Main.selection.equals("Tạo bộ từ vựng") == false && CN.equals("Ghép Bộ Từ Vựng")){
            GhepBoTuVungView();
        }
        else if(Main.selection.equals("Tạo bộ từ vựng") == false && CN.equals("Xóa Từ")){                             
            XoaTu();
           }
        else if(Main.selection.equals("Tạo bộ từ vựng") == false && CN.equals("Sửa Từ")){
            SuaTu();
        }
        else if(Main.selection.equals("Tạo bộ từ vựng") == false && CN.equals("Xóa Bộ Từ Vựng")){
            XoaBoTuVung();
        }
        else{
            
            jPanel2.setVisible(false);
            JOptionPane.showMessageDialog(rootPane, "Bộ từ vựng đã chọn không hợp lệ. Mời bạn vui lòng kiểm tra lại!");
        }

    }//GEN-LAST:event_buttonBDActionPerformed

    private void textBTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBTVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBTVActionPerformed

    private void buttonChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChonActionPerformed
        try {
            if(CN.equals("Xóa Từ")){
                Main.mapAV1.removeWord(En, Main.selection);
                Main.mapAV1.clear();
                Main.LoadAV1();
                listTu.clear();
                listTu = Main.mapAV1.toArrayList();
                cbbTu.removeAllItems();
                for(int i =0; i<listTu.size(); i++)
                    cbbTu.addItem(listTu.get(i));
                
                if(listTu.contains(En))
                    JOptionPane.showMessageDialog(rootPane, "Xóa từ thành công");
                else JOptionPane.showMessageDialog(rootPane, "Xóa từ không thành công");
            }
            else if(CN.equals("Thêm Từ")){
                String check = Main.selection;
                Main.selection = textBTV.getText();
                word Word = new word();
                Word.setDate(null);
                Word.setEn(textNew.getText());
                Word.setVn(textNghia.getText());
                Word.setPrn(textPA.getText());
                if(!Main.listChuDe.contains(textBTV.getText())){
                    TaoBoTuVung(textBTV.getText());
                }
                Main.mapAV1.addNewWord(Word, textBTV.getText());
                Main.mapAV1.clear();
                Main.LoadAV1();
                En = textNew.getText();
                if(Main.mapAV1.containsKey(En)){  
                    if(check.equals("Tạo bộ từ vựng")){
                        cbbCD.removeItem("Tạo bộ từ vựng");
                        cbbCD.addItem(textBTV.getText());
                        cbbCD.addItem("Tạo bộ từ vựng");
                    }
                    JOptionPane.showMessageDialog(rootPane, "Thêm từ thành công");
                }
                else JOptionPane.showMessageDialog(rootPane, "Thêm từ không thành công");
                
                
            }
            else if(CN.equals("Sửa Từ")){               
                word Word = new word();
                Word.setEn(textNew.getText());
                Word.setVn(textNghia.getText());
                Word.setPrn(textPA.getText());                
                Main.mapAV1.removeWord(En, Main.selection);
                Main.mapAV1.addNewWord(Word, Main.selection);
                
                Main.mapAV1.clear();
                Main.LoadAV1();            
                if(Main.mapAV1.containsKey(Word.getEn())){               
                    JOptionPane.showMessageDialog(rootPane, "Sửa từ thành công");
                    listTu.clear();
                    listTu = Main.mapAV1.toArrayList();
                    cbbTu.removeAllItems();
                    for(int i = 0; i<listTu.size(); i++)
                        cbbTu.addItem(listTu.get(i));
                }
                else JOptionPane.showMessageDialog(rootPane, "Sửa từ không thành công");}
            else  if(CN.equals("Ghép Bộ Từ Vựng")){
                String name = textNew.getText();
                GhepBoTuVungCode(Main.selection, En, name);
                Main.listChuDe.clear();
                Main.LoadList();
                if(Main.listChuDe.contains(name)){
                cbbCD.removeAllItems();
                for(int i =0; i < Main.listChuDe.size(); i++)
                    cbbCD.addItem(Main.listChuDe.get(i));
                cbbCD.addItem("Tạo bộ từ vựng");
                JOptionPane.showMessageDialog(rootPane, "Ghép bộ từ vựng thành công");}
                else JOptionPane.showMessageDialog(rootPane, "Ghép bộ từ vựng không thành công");
            }
            else if(CN.equals("Xóa Bộ Từ Vựng")){
                XoaBoTuVung(Main.selection);
                Main.listChuDe.clear();
                
                Main.LoadList();
                
                if(Main.listChuDe.contains(Main.selection))
                    JOptionPane.showMessageDialog(rootPane, "Xóa bộ từ vựng không thành công");
                else{
                    cbbCD.removeItem(Main.selection);
                    cbbCD.removeItem("Tạo bộ từ vựng");
                    cbbCD.addItem("Tạo bộ từ vựng");
                    JOptionPane.showMessageDialog(rootPane, "Xóa bộ từ vựng thành công");
                    }
            }
            
            
        } catch (Exception ee) {}
        
    }//GEN-LAST:event_buttonChonActionPerformed

    private void cbbTuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbTuItemStateChanged
        if(cbbTu.getItemCount() > 0 && !CN.equals("Ghép Bộ Từ Vựng")){
        En = cbbTu.getSelectedItem().toString();
        textNghia.setText(Main.mapAV1.getmapVn(En));
        textPA.setText(Main.mapAV1.getmapPrn(En));}
        else if(cbbTu.getItemCount() > 0 && CN.equals("Ghép Bộ Từ Vựng")){
            En = cbbTu.getSelectedItem().toString();
            
        }
        else ;
        
    }//GEN-LAST:event_cbbTuItemStateChanged

    private void cbbCDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbCDItemStateChanged

         Main.selection = cbbCD.getSelectedItem().toString();
    }//GEN-LAST:event_cbbCDItemStateChanged

    private void cbbDSTVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbDSTVItemStateChanged
        CN = cbbDSTV.getSelectedItem().toString();
    }//GEN-LAST:event_cbbDSTVItemStateChanged

    private void buttonHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHDActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Bạn thêm hình ảnh vào hoặc chỉnh sửa theo đường dẫn " + System.getProperty("user.dir") + "/images/" + "\n"
                + "Tên ảnh phải đặt trùng với tên từ muốn thêm và ở định dạng .jpeg");
    }//GEN-LAST:event_buttonHDActionPerformed

    private void buttonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHuyActionPerformed
        jPanel2.setVisible(false);
    }//GEN-LAST:event_buttonHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDQLBTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDQLBTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDQLBTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDQLBTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GDQLBTV().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GDQLBTV.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbAnh;
    private javax.swing.JLabel LbBTV;
    private javax.swing.JLabel LbNew;
    private javax.swing.JLabel LbNghĩa;
    private javax.swing.JLabel LbPA;
    private javax.swing.JLabel LbXoaOrTD;
    private javax.swing.JButton buttonBD;
    private javax.swing.JButton buttonChon;
    private javax.swing.JButton buttonHD;
    private javax.swing.JButton buttonHuy;
    private javax.swing.JButton buttonTC;
    private javax.swing.JButton buttonThoat;
    private javax.swing.JComboBox<String> cbbCD;
    private javax.swing.JComboBox<String> cbbDSTV;
    private javax.swing.JComboBox<String> cbbTu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField textBTV;
    private javax.swing.JTextField textNew;
    private javax.swing.JTextField textNghia;
    private javax.swing.JTextField textPA;
    // End of variables declaration//GEN-END:variables

    public void XoaTu(){
        
        LbXoaOrTD.setText("Từ cần xóa");
        LbNew.setText("Bộ từ vựng");
        textNew.setText(Main.selection);     
        LbBTV.setVisible(false);
        textBTV.setVisible(false);
        buttonChon.setText(CN);
        LbXoaOrTD.setVisible(true);
        cbbTu.setVisible(true);
        textNghia.setText(Main.mapAV1.getmapVn(En));
        textPA.setText(Main.mapAV1.getmapPrn(En));
        LbAnh.setVisible(true);
        LbPA.setVisible(true);
        LbNew.setVisible(true);
        textNew.setVisible(true);
        textPA.setVisible(true);
        textNghia.setVisible(true);
        LbNghĩa.setVisible(true);
        buttonHD.setVisible(true); 
        jPanel2.setVisible(true);
    }
    public void ThemTu(){
        LbNew.setText("Từ muốn thêm");
        if(Main.selection.equals("Tạo bộ từ vựng"))
            textBTV.setText("");
        else
            textBTV.setText(Main.selection);
        buttonChon.setText(CN);
        textNew.setText("");
        textNghia.setText("");
        textPA.setText("");
        LbBTV.setVisible(true);
        textBTV.setVisible(true);
        LbAnh.setVisible(true);
        LbPA.setVisible(true);
        LbNew.setVisible(true);
        textNew.setVisible(true);
        textPA.setVisible(true);
        textNghia.setVisible(true);
        buttonHD.setVisible(true);       
        LbXoaOrTD.setVisible(false);
        cbbTu.setVisible(false);
        LbNghĩa.setVisible(true);
        jPanel2.setVisible(true);
    }
    public void SuaTu(){
        LbXoaOrTD.setText("Từ cần sửa");
        LbXoaOrTD.setVisible(true);
        textNew.setVisible(true);
        LbNew.setText("Sửa thành");
        textNew.setText("");
        textBTV.setText(Main.selection);
        LbBTV.setVisible(true);
        textBTV.setVisible(true);
        buttonChon.setText(CN);
        LbNew.setVisible(true);
        cbbTu.setVisible(true);
        textNghia.setText(Main.mapAV1.getmapVn(En));
        textPA.setText(Main.mapAV1.getmapPrn(En));
        LbPA.setVisible(true);
        textPA.setVisible(true);
        jPanel2.setVisible(true);
    }
    public void GhepBoTuVungView(){
        LbXoaOrTD.setText("Ghép với");
        LbNew.setText("Tên bộ từ vựng mới");
        textNew.setText("");
        textBTV.setText(Main.selection);
        LbBTV.setVisible(true);
        textBTV.setVisible(true);
        buttonChon.setText("Ghép");
        LbXoaOrTD.setVisible(true);
        cbbTu.setVisible(true);
        textNghia.setVisible(false);
        textPA.setVisible(false);
        LbPA.setVisible(false);
        LbNghĩa.setVisible(false);
        LbAnh.setVisible(false);
        buttonHD.setVisible(false);
        jPanel2.setVisible(true);
        
        
    }
    public void XoaBoTuVung(){
        LbBTV.setVisible(true);
        textBTV.setVisible(true);
        textBTV.setText(Main.selection);
        buttonChon.setText("Xóa");
        LbXoaOrTD.setVisible(false);
        cbbTu.setVisible(false);
        textNghia.setVisible(false);
        textPA.setVisible(false);
        LbPA.setVisible(false);
        LbNghĩa.setVisible(false);
        LbNew.setVisible(false);
        textNew.setVisible(false);
        LbAnh.setVisible(false);
        buttonHD.setVisible(false);
        jPanel2.setVisible(true);
        
    }
    public void GhepBoTuVungCode(String a, String b, String name)
    {
        Excel e = new Excel();
        HashMapHandling m1 = new HashMapHandling();
        HashMapHandling m2 = new HashMapHandling();
        try{
            m1 = e.readMapEn(MakeFilePath(a));
            m2 = e.readMapEn(MakeFilePath(b));
            m1.connect(m2);
            e.writeMap(m1, MakeFilePath(name));
        }
        catch(Exception ex)
        {
        }
        //Ghép xong 2 file a và b rồi ghi ra file name
        //Xóa a và b khỏi List từ rồi thêm name vào
        Main.listChuDe.add(name);
        //Main.listChuDe.remove(a);
        //Main.listChuDe.remove(b);
        try {
            e.writeList(Main.listChuDe, MakeFilePath("list"));
        } catch (Exception ex) {
        }
    }
    public void TaoBoTuVung(String name)
    {
        Main.listChuDe.add(name);
        Excel e = new Excel();
        HashMapHandling m = new HashMapHandling();
        try{
            e.writeMap(m, MakeFilePath(name));
            e.writeList(Main.listChuDe, MakeFilePath("list"));
        }
        catch(Exception ex)
        {
        }
    }
    public void XoaBoTuVung(String name)
    {
        Main.listChuDe.remove(name);
        Excel e = new Excel();
        HashMapHandling m = new HashMapHandling();
        try{
            e.writeMap(m, MakeFilePath(name));
            e.writeList(Main.listChuDe, MakeFilePath("list"));
        }
        catch(Exception ex)
        {
        }
    }
}
