/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Vu Ngoc Chi
 */
public class GDTrangChu extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form GDTrangChu
     */
    
    public GDTrangChu() {
        initComponents();
        
        buttonThoat.addActionListener(this);
        buttonTVHN.addActionListener(this);
        buttonTK.addActionListener(this);
        buttonTVNN.addActionListener(this);
        buttonKT.addActionListener(this);
        buttonQLBTV.addActionListener(this);
        buttonHT.addActionListener(this);
        buttonTKDL.addActionListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonTK = new javax.swing.JButton();
        buttonKT = new javax.swing.JButton();
        buttonThoat = new javax.swing.JButton();
        buttonTVNN = new javax.swing.JButton();
        buttonTKDL = new javax.swing.JButton();
        buttonTVHN = new javax.swing.JButton();
        buttonQLBTV = new javax.swing.JButton();
        buttonHT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(120, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/labelChinh.gif"))); // NOI18N

        buttonTK.setBackground(new java.awt.Color(0, 255, 255));
        buttonTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonTK.setForeground(new java.awt.Color(255, 51, 153));
        buttonTK.setText("TÌM KIẾM");
        buttonTK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTKActionPerformed(evt);
            }
        });

        buttonKT.setBackground(new java.awt.Color(0, 255, 255));
        buttonKT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonKT.setForeground(new java.awt.Color(255, 51, 153));
        buttonKT.setText("KIỂM TRA");
        buttonKT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKTActionPerformed(evt);
            }
        });

        buttonThoat.setBackground(new java.awt.Color(0, 255, 255));
        buttonThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonThoat.setForeground(new java.awt.Color(255, 51, 153));
        buttonThoat.setText("THOÁT");
        buttonThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThoatActionPerformed(evt);
            }
        });

        buttonTVNN.setBackground(new java.awt.Color(0, 255, 255));
        buttonTVNN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonTVNN.setForeground(new java.awt.Color(255, 51, 153));
        buttonTVNN.setText("TỪ VỰNG NHẮC NHỞ");
        buttonTVNN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonTVNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTVNNActionPerformed(evt);
            }
        });

        buttonTKDL.setBackground(new java.awt.Color(0, 255, 255));
        buttonTKDL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonTKDL.setForeground(new java.awt.Color(255, 51, 153));
        buttonTKDL.setText("THỐNG KÊ DỮ LIỆU");
        buttonTKDL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonTKDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTKDLActionPerformed(evt);
            }
        });

        buttonTVHN.setBackground(new java.awt.Color(0, 255, 255));
        buttonTVHN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonTVHN.setForeground(new java.awt.Color(255, 0, 153));
        buttonTVHN.setText("TỪ VỰNG HÔM NAY");
        buttonTVHN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonTVHN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTVHNActionPerformed(evt);
            }
        });

        buttonQLBTV.setBackground(new java.awt.Color(0, 255, 255));
        buttonQLBTV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonQLBTV.setForeground(new java.awt.Color(255, 51, 153));
        buttonQLBTV.setText("QUẢN LÍ BỘ TỪ VỰNG");
        buttonQLBTV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonQLBTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQLBTVActionPerformed(evt);
            }
        });

        buttonHT.setBackground(new java.awt.Color(0, 255, 255));
        buttonHT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonHT.setForeground(new java.awt.Color(255, 51, 153));
        buttonHT.setText("HỌC TỪ");
        buttonHT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHTActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/label1.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/label2.jpg"))); // NOI18N

        jLabel4.setText("@Author: Vũ Ngọc Chi - Nguyễn Thành Đại");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/welkom10.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(146, 146, 146))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonKT, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonTK, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonTVNN, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonTVHN, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonTKDL, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonQLBTV, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonHT, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTK, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHT, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKT, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonQLBTV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTVNN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTKDL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonTVHN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(62, 62, 62))))))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Label1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTKActionPerformed

    private void buttonKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonKTActionPerformed

    private void buttonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonThoatActionPerformed

    private void buttonTVNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTVNNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTVNNActionPerformed

    private void buttonTKDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTKDLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTKDLActionPerformed

    private void buttonTVHNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTVHNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTVHNActionPerformed

    private void buttonQLBTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQLBTVActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_buttonQLBTVActionPerformed

    private void buttonHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonHTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDTrangChu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHT;
    private javax.swing.JButton buttonKT;
    private javax.swing.JButton buttonQLBTV;
    private javax.swing.JButton buttonTK;
    private javax.swing.JButton buttonTKDL;
    private javax.swing.JButton buttonTVHN;
    private javax.swing.JButton buttonTVNN;
    private javax.swing.JButton buttonThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(buttonTK)){
            buttonTKClick();
        }
        else if(e.getSource().equals(buttonKT)){
            try {
                buttonKTClick();
            } catch (IOException ex) {
                Logger.getLogger(GDTrangChu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(e.getSource().equals(buttonTVNN)){
            buttonTVNNClick();
        }
        else if(e.getSource().equals(buttonTVHN)){
            buttonTVHNClick();
        }
        else if(e.getSource().equals(buttonTKDL)){
            buttonTKDLClick();
        }
        else if(e.getSource().equals(buttonHT)){
            buttonHTClick();
        }
        else if(e.getSource().equals(buttonQLBTV)){
            try {
                buttonQLBTVClick();
            } catch (IOException ex) {
                Logger.getLogger(GDTrangChu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else buttonThoatClick();
        
        }
    public void buttonThoatClick(){
        System.exit(0);
        
    }
    public void buttonTKClick(){
        
        new GDTimKiem().setVisible(true);
        this.dispose();
    }
    public void buttonKTClick() throws IOException{
        new GDKiemTra().setVisible(true);
        this.dispose();
        
    }
    public void buttonQLBTVClick() throws IOException{
        new GDQLBTV().setVisible(true);
        this.dispose();
               
    }
    public void buttonHTClick(){        
        GDHocTu.ChucNang= "HocTu";
        new GDChuDe().setVisible(true);
        this.dispose();
    }
    public void buttonTVHNClick(){
        GDHocTu.ChucNang= "TVHN";
        new GDHocTu().setVisible(true);
        this.dispose();
        
    }
    public void buttonTVNNClick(){
        GDHocTu.ChucNang = "TVNN";
        new GDHocTu().setVisible(true);
        this.dispose();
    }
    public void buttonTKDLClick(){
        
    }
}
