/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import static javax.swing.SwingConstants.BOTTOM;
import static javax.swing.SwingConstants.CENTER;
import controler.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Vu Ngoc Chi
 */
public class GDVietAnh extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form GDANhViet
     */
    public GDVietAnh() throws IOException {
        initComponents();
        buttonTC.addActionListener(this);
        buttonThoat.addActionListener(this);
        buttonTK.addActionListener(this);
        buttonAV.addActionListener(this);
        Main.LoadVA();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        buttonTK = new javax.swing.JButton();
        buttonThoat = new javax.swing.JButton();
        buttonTC = new javax.swing.JButton();
        Lbanh = new javax.swing.JLabel();
        buttonAV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIG - TREE");
        setLocation(new java.awt.Point(130, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Viet_Nam-02.png"))); // NOI18N

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        buttonTK.setBackground(new java.awt.Color(255, 153, 204));
        buttonTK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonTK.setForeground(new java.awt.Color(102, 0, 255));
        buttonTK.setText("Tìm Kiếm");

        buttonThoat.setBackground(new java.awt.Color(0, 255, 51));
        buttonThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonThoat.setForeground(new java.awt.Color(153, 0, 0));
        buttonThoat.setText("Thoát");

        buttonTC.setBackground(new java.awt.Color(0, 255, 51));
        buttonTC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonTC.setForeground(new java.awt.Color(153, 0, 0));
        buttonTC.setText("Trang Chủ");

        Lbanh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Lbanh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Lbanh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonAV.setBackground(new java.awt.Color(0, 255, 51));
        buttonAV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonAV.setForeground(new java.awt.Color(153, 0, 0));
        buttonAV.setText("Anh - Việt");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbanh)
                .addGap(463, 463, 463))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonThoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonTK)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(buttonAV, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(909, Short.MAX_VALUE)
                    .addComponent(buttonTC, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(117, 117, 117)
                .addComponent(Lbanh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(buttonAV)
                .addGap(70, 70, 70)
                .addComponent(buttonThoat)
                .addGap(33, 33, 33))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(545, Short.MAX_VALUE)
                    .addComponent(buttonTC)
                    .addGap(80, 80, 80)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            buttonTKClick();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     * @throws java.io.FileNotFoundException
     * @throws jxl.read.biff.BiffException
     */
        
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDVietAnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDVietAnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDVietAnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDVietAnh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GDVietAnh().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GDVietAnh.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbanh;
    private javax.swing.JButton buttonAV;
    private javax.swing.JButton buttonTC;
    private javax.swing.JButton buttonTK;
    private javax.swing.JButton buttonThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(buttonTK))
            buttonTKClick();
        else if(e.getSource().equals(buttonTC))
            buttonTCClick();
        else if(e.getSource().equals(buttonAV))
            try {
                buttonAVClick();
        } catch (IOException ex) {
            Logger.getLogger(GDVietAnh.class.getName()).log(Level.SEVERE, null, ex);
        }
        else    
            buttonThoatClick();
        
    }
    public void buttonTKClick(){
        
        

        String vn = jTextField1.getText();
        String en = new String();
        String concat = new String();
        ImageIcon icon;
        if(Main.mapVA.containsKey(vn)==false) {
            concat = "Word can not found";
            icon = new ImageIcon(getClass().getResource("/data/noimg.jpeg"));
        }
        else
        {
        en = Main.mapVA.getmapEn(vn);
        concat = en.concat(" : "+ Main.mapVA.getmapPrn(vn));
        try
            {
            icon = new ImageIcon(getClass().getResource("/data/"+en+".jpeg"));
            }
        catch(Exception eee)
            {
                icon = new ImageIcon(getClass().getResource("/data/noimg.jpeg"));
            }
        }
        Lbanh.setIcon(icon);
        Lbanh.setText(concat);
        Lbanh.setHorizontalTextPosition(CENTER);
        Lbanh.setVerticalTextPosition(BOTTOM);
    }
    public void buttonTCClick(){
        new GDTrangChu().setVisible(true);
        this.dispose();
        
    }
    public void buttonAVClick() throws IOException{
        new GDAnhViet().setVisible(true);
        this.dispose();
        
    }
    public void buttonThoatClick(){
        System.exit(0);
        
    }
}
